apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoservers-deployment
  namespace: webservers
spec:
  replicas: 3
  selector:
    matchLabels:
      app: echoserver
  template:
    metadata:
      labels:
        app: echoserver
    spec:
      containers:
      - name: echoserver
        image: sdulisoff/echoserver:v01
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: AUTHOR
          value: "Stasik"
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
      imagePullSecrets:
      - name: regcred